"""User preferences change 29.11

Revision ID: 650630c198e8
Revises: 5e509cba6053
Create Date: 2024-11-29 01:26:20.049827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '650630c198e8'
down_revision: Union[str, None] = '5e509cba6053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_info_full_name', table_name='user_info')
    op.drop_index('ix_user_info_id', table_name='user_info')
    op.drop_table('user_info')
    op.drop_index('ix_accounts_active', table_name='accounts')
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_index('ix_accounts_id', table_name='accounts')
    op.drop_index('ix_accounts_role', table_name='accounts')
    op.drop_index('ix_accounts_user_name', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_info_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('role', sa.VARCHAR(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_user_name', 'accounts', ['user_name'], unique=1)
    op.create_index('ix_accounts_role', 'accounts', ['role'], unique=False)
    op.create_index('ix_accounts_id', 'accounts', ['id'], unique=False)
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=1)
    op.create_index('ix_accounts_active', 'accounts', ['active'], unique=False)
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('avatar', sa.BLOB(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_info_id', 'user_info', ['id'], unique=False)
    op.create_index('ix_user_info_full_name', 'user_info', ['full_name'], unique=False)
    # ### end Alembic commands ###
