export const SLICE_KEYS = {
   APPLICATION_SLICE: "APPLICATION_SLICE",
   CURRENT_USER_SLICE: "CURRENT_USER_SLICE",
   ADMIN_PANEL_SLICE: "ADMIN_PANEL_SLICE",
   TASKS_SLICE: "TASKS_SLICE",
   TIMESHEET_SLICE: "TIMESHEET_SLICE",
   PROJECTS_SLICE: "PROJECTS_SLICE",
}